feature: provide a way for plugins to get the list of serial ports
SignalK/signalk-server pull request #1110
Opened 2020-08-28 14:08 UTC by sbender9

This includes making so `plugin.schema()` and `plugin.schemaUI()` can return a promise

2020-08-28 14:09 UTC, sbender9 commented
Example usage here: https://github.com/sbender9/signalk-serial-ports-example-plugin

2020-09-09 20:05 UTC, tkurki requested changes
I started down the rabbit hole by looking into why there are no ts bindings for @serialport/binddings, making that @ts-ignore needed. 

And I realised that I've probably introduced a wrong way to get a serialport listing.

Docs at https://serialport.io/docs/api-stream#serialportlist say that you should
```
const SerialPort = require('serialport')
SerialPort.list().then(x => console.log(x))
```
so it looks like instead of adding to the injury we should replace both instances of @serialport/bindings with the proper listing method.

2020-09-10 18:08 UTC, tkurki commented on src/interfaces/plugins.ts
> +// @ts-ignore
I think there are types for serialport, installing them should get rid of the need for the ignore and then we can return something other than any below

2020-09-11 14:06 UTC, tkurki commented on src/serverroutes.js
> +    listAllSerialPorts().then(ports => {
no need for the curly braces

2020-09-11 15:17 UTC, sbender9 commented
I don't understand why lint is failing. I did not change anything with that line of code.  What am I'm missing??

2020-09-11 15:59 UTC, tkurki commented
You moved that from .js to .ts - differerent rules apply.

2020-09-11 16:02 UTC, tkurki commented
There's fs.promises.readdir since 10.0.0, time to use that?

2020-09-11 16:32 UTC, sbender9 commented
Shoot I was looking at the wrong file... (plugins.ts), let me switch to fs.promises...

2020-09-14 17:51 UTC, merged