Fix: Minimum version check
SignalK/signalk-server pull request #1578
Opened 2023-07-14 13:23 UTC by JacoKoster

Fixes #1573

2023-07-18 07:46 UTC, tkurki requested changes

2023-07-18 07:46 UTC, tkurki commented on bin/signalk-server
> +if (!semver.satisfies(process.version, version)) {
This is a nice idea in theory, but in practise the minimum is now 16 (we are running tests with it so we don't accidentally mess that up).

I think this should
- !== 18 => log "The recommended version of Node.js is 18, you are running ${process.version}"
- <16  => error log what this does now

2023-07-18 07:46 UTC, tkurki commented on bin/signalk-server
> +  console.log(`The installed version of node (${process.version}) is older than the required minimum version (${version}). See https://github.com/SignalK/signalk-server/wiki/Updating-to-Node.js-18 fo
I reorganised the wiki, this should point to non version specific instructions at https://github.com/SignalK/signalk-server/wiki/Installing-and-Updating-Node.js

2023-07-18 08:00 UTC, JacoKoster commented on bin/signalk-server
> +if (!semver.satisfies(process.version, version)) {
Looking at when 16 goes out of maintenance, it might be worthwhile to make a new issue to test and upgrade to 18?

2023-07-19 13:06 UTC, tkurki commented on bin/signalk-server
> +if (!semver.satisfies(process.version, version)) {
Yep, was thinking about the same thing. Docker images already use 18.

But going forward we’ll probably still have minimum separate from recommended that would be latest lts.

2023-07-20 06:45 UTC, tkurki commented on bin/signalk-server
> +if (!semver.satisfies(process.version, version)) {
#1584

2023-07-20 07:26 UTC, tkurki approved these changes

2023-07-20 07:26 UTC, merged

2023-07-20 07:27 UTC, tkurki commented
Fyi @sailoog @mgrouch

2023-07-20 15:19 UTC, mgrouch commented
@tkurki 

BBN Marine OS is already with node 18 and SignalK 2.0

2023-07-20 16:37 UTC, sailoog commented
Thanks for notifying. We already changed from node 16 to node 18 in openplotter-signalk-installer v3.2.0. Any existing node 16 installation is converted to a node 18 installation silently. Any queryable setting would help automate this process, any ideas?

2023-07-20 18:36 UTC, tkurki commented
New downloads being on node 18 is one thing. There’s also existing installations: if somebody just updates their existing setup’s sk their system will break if min nodejs check is not met. Not that this PR changes much: older versions will break anyway, this just gives a nicer log message.

2023-07-20 18:55 UTC, sailoog commented
> What would like to query?

recommended node version

> New downloads being on node 18 is one thing. There’s also existing installations: if somebody just updates their existing setup’s sk their system will break if min nodejs check is not met. Not that this PR changes much: older versions will break anyway, this just gives a nicer log message.

yes, and that is solved in openplotter v3 because we decide when to publish a new openplotter-signalk-installer package containing the new recommended node version. Node and sk will update without breaking anything but it could take some days until we realize that you changed the recommended version, so a system to check this could be nice to automatically update existing systems.

2023-07-21 06:33 UTC, tkurki commented
I think the recommendation changes so infrequently that we can do with just keeping syncing between people. And recommendation not being 100% up to date is not crucial.